---
- name: setup of jenkins server
  hosts: jenkinsserver
  tasks: 
   - name: install java,git,maven
     apt: 
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items: 
      - {a: openjdk-8-jdk,b: no}
      - {a: git,b: no}
      - {a: maven,b: no}
   - name: downloads jenkins.war
     get_url: 
      url: https://get.jenkins.io/war-stable/2.263.4/jenkins.war
      dest: /tmp
- name: setup tomcat on qa and prodserver
  hosts: servers  
  tasks: 
   - name: install tomcat8 and tomcat8-admin
     apt: 
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: tomcat8,b: yes}
      - {a: tomcat8-admin,b: no}
   - name: copy tomcat-users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat8     
