---
- name: create multiple users and create files/dirs in users home dir
  hosts: all
  tasks: 
   - name: create multiple users
     user:
      name: "{{item.a}}"
      password: "{{item.b}}"
      home: "{{item.C}}"
      with_items: 
      - {a: ravi,b: ravikumar,c: /home/ravi}
      - {a: raju,b: ravikumar,c: /home/ubuntu/raju}
   - name: creating files/dirs in users home dir
     file:
      name: "{{item.a}}"
      state: "{{item.b}}"
     witm_items: 
      - {a: /home/ravi/file1,b: touch}
      - {a: /home/ubuntu/raju/dir1,b: directory}
           
